[2025-05-26T03:36:28.255+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:36:28.269+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:36:28.269+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-05-26T03:36:28.288+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): create_table_clean> on 2025-05-01 00:00:00+00:00
[2025-05-26T03:36:28.299+0000] {standard_task_runner.py:57} INFO - Started process 6434 to run task
[2025-05-26T03:36:28.307+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_clean', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpb8hjnbz4']
[2025-05-26T03:36:28.312+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask create_table_clean
[2025-05-26T03:36:28.420+0000] {task_command.py:410} INFO - Running <TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [running]> on host 65cea7b09e55
[2025-05-26T03:36:28.571+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_clean' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-26T03:36:28.575+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_pipeline.py", line 116, in create_table_clean
    CREATE TABLE IF NOT EXISTS {SCHEMA_CLEAN}.{TABLE_CLEAN} (
NameError: name 'TABLE_CLEAN' is not defined
[2025-05-26T03:36:28.596+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline, task_id=create_table_clean, execution_date=20250501T000000, start_date=20250526T033628, end_date=20250526T033628
[2025-05-26T03:36:28.614+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task create_table_clean (name 'TABLE_CLEAN' is not defined; 6434)
[2025-05-26T03:36:28.638+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-05-26T03:36:28.705+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-26T03:38:13.744+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:38:13.763+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:38:13.764+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-05-26T03:38:13.781+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): create_table_clean> on 2025-05-01 00:00:00+00:00
[2025-05-26T03:38:13.793+0000] {standard_task_runner.py:57} INFO - Started process 6469 to run task
[2025-05-26T03:38:13.804+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_clean', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpzltr_xp8']
[2025-05-26T03:38:13.811+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask create_table_clean
[2025-05-26T03:38:13.921+0000] {task_command.py:410} INFO - Running <TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [running]> on host 65cea7b09e55
[2025-05-26T03:38:14.062+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_clean' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-26T03:38:14.093+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-26T03:38:14.113+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_clean, execution_date=20250501T000000, start_date=20250526T033813, end_date=20250526T033814
[2025-05-26T03:38:14.173+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-05-26T03:38:14.228+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-26T03:41:48.740+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:41:48.757+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:41:48.758+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-05-26T03:41:48.777+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): create_table_clean> on 2025-05-01 00:00:00+00:00
[2025-05-26T03:41:48.789+0000] {standard_task_runner.py:57} INFO - Started process 6535 to run task
[2025-05-26T03:41:48.796+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_clean', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpx4176b85']
[2025-05-26T03:41:48.801+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask create_table_clean
[2025-05-26T03:41:48.891+0000] {task_command.py:410} INFO - Running <TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [running]> on host 65cea7b09e55
[2025-05-26T03:41:49.067+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_clean' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-26T03:41:49.094+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-26T03:41:49.121+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_clean, execution_date=20250501T000000, start_date=20250526T034148, end_date=20250526T034149
[2025-05-26T03:41:49.173+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-05-26T03:41:49.226+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-26T03:49:19.580+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:49:19.597+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:49:19.598+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-05-26T03:49:19.617+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): create_table_clean> on 2025-05-01 00:00:00+00:00
[2025-05-26T03:49:19.632+0000] {standard_task_runner.py:57} INFO - Started process 6672 to run task
[2025-05-26T03:49:19.640+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_clean', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp3fgp6fo2']
[2025-05-26T03:49:19.645+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask create_table_clean
[2025-05-26T03:49:19.734+0000] {task_command.py:410} INFO - Running <TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [running]> on host 65cea7b09e55
[2025-05-26T03:49:19.861+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_clean' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-26T03:49:19.881+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-26T03:49:19.899+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_clean, execution_date=20250501T000000, start_date=20250526T034919, end_date=20250526T034919
[2025-05-26T03:49:19.973+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-05-26T03:49:20.022+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-26T03:58:29.329+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:58:29.351+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:58:29.351+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-05-26T03:58:29.372+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): create_table_clean> on 2025-05-01 00:00:00+00:00
[2025-05-26T03:58:29.388+0000] {standard_task_runner.py:57} INFO - Started process 6847 to run task
[2025-05-26T03:58:29.402+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_clean', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp4t15hgkr']
[2025-05-26T03:58:29.407+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask create_table_clean
[2025-05-26T03:58:29.525+0000] {task_command.py:410} INFO - Running <TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [running]> on host 65cea7b09e55
[2025-05-26T03:58:29.677+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_clean' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-26T03:58:29.696+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-26T03:58:29.723+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_clean, execution_date=20250501T000000, start_date=20250526T035829, end_date=20250526T035829
[2025-05-26T03:58:29.767+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-05-26T03:58:29.854+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-26T04:05:50.642+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T04:05:50.663+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T04:05:50.664+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-05-26T04:05:50.693+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): create_table_clean> on 2025-05-01 00:00:00+00:00
[2025-05-26T04:05:50.716+0000] {standard_task_runner.py:57} INFO - Started process 113 to run task
[2025-05-26T04:05:50.724+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_clean', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp4ix9tf65']
[2025-05-26T04:05:50.730+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask create_table_clean
[2025-05-26T04:05:50.822+0000] {task_command.py:410} INFO - Running <TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [running]> on host 419e61ae62e7
[2025-05-26T04:05:50.953+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_clean' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-26T04:05:50.989+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-26T04:05:51.008+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_clean, execution_date=20250501T000000, start_date=20250526T040550, end_date=20250526T040551
[2025-05-26T04:05:51.059+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-05-26T04:05:51.113+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-26T04:17:36.690+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T04:17:36.709+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T04:17:36.710+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-05-26T04:17:36.727+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): create_table_clean> on 2025-05-01 00:00:00+00:00
[2025-05-26T04:17:36.743+0000] {standard_task_runner.py:57} INFO - Started process 317 to run task
[2025-05-26T04:17:36.752+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_clean', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp7285b04o']
[2025-05-26T04:17:36.756+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask create_table_clean
[2025-05-26T04:17:36.857+0000] {task_command.py:410} INFO - Running <TaskInstance: data_pipeline.create_table_clean scheduled__2025-05-01T00:00:00+00:00 [running]> on host 419e61ae62e7
[2025-05-26T04:17:36.992+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_clean' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-26T04:17:37.011+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-26T04:17:37.033+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_clean, execution_date=20250501T000000, start_date=20250526T041736, end_date=20250526T041737
[2025-05-26T04:17:37.087+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-05-26T04:17:37.134+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
