[2025-05-26T03:33:36.471+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:33:36.483+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:33:36.484+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-05-26T03:33:36.502+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): create_table_raw> on 2025-05-01 00:00:00+00:00
[2025-05-26T03:33:36.513+0000] {standard_task_runner.py:57} INFO - Started process 6384 to run task
[2025-05-26T03:33:36.524+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_raw', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmplf9i8iwj']
[2025-05-26T03:33:36.529+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask create_table_raw
[2025-05-26T03:33:36.639+0000] {task_command.py:410} INFO - Running <TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [running]> on host 65cea7b09e55
[2025-05-26T03:33:36.760+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-26T03:33:36.763+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_pipeline.py", line 48, in create_table_raw
    CREATE SCHEMA IF NOT EXISTS {SCHEMA};
NameError: name 'SCHEMA' is not defined
[2025-05-26T03:33:36.777+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline, task_id=create_table_raw, execution_date=20250501T000000, start_date=20250526T033336, end_date=20250526T033336
[2025-05-26T03:33:36.793+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task create_table_raw (name 'SCHEMA' is not defined; 6384)
[2025-05-26T03:33:36.813+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-05-26T03:33:36.876+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-26T03:36:10.312+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:36:10.327+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:36:10.328+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-05-26T03:36:10.347+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): create_table_raw> on 2025-05-01 00:00:00+00:00
[2025-05-26T03:36:10.359+0000] {standard_task_runner.py:57} INFO - Started process 6418 to run task
[2025-05-26T03:36:10.366+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_raw', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp41l1rq_m']
[2025-05-26T03:36:10.373+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask create_table_raw
[2025-05-26T03:36:10.476+0000] {task_command.py:410} INFO - Running <TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [running]> on host 65cea7b09e55
[2025-05-26T03:36:10.597+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-26T03:36:10.613+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-26T03:36:10.630+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_raw, execution_date=20250501T000000, start_date=20250526T033610, end_date=20250526T033610
[2025-05-26T03:36:10.660+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-05-26T03:36:10.735+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-26T03:37:53.311+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:37:53.331+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:37:53.331+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-05-26T03:37:53.351+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): create_table_raw> on 2025-05-01 00:00:00+00:00
[2025-05-26T03:37:53.362+0000] {standard_task_runner.py:57} INFO - Started process 6460 to run task
[2025-05-26T03:37:53.370+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_raw', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpz5ijklqj']
[2025-05-26T03:37:53.375+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask create_table_raw
[2025-05-26T03:37:53.503+0000] {task_command.py:410} INFO - Running <TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [running]> on host 65cea7b09e55
[2025-05-26T03:37:53.664+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-26T03:37:53.688+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-26T03:37:53.707+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_raw, execution_date=20250501T000000, start_date=20250526T033753, end_date=20250526T033753
[2025-05-26T03:37:53.788+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-05-26T03:37:53.867+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-26T03:41:04.607+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:41:04.632+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:41:04.632+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-05-26T03:41:04.654+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): create_table_raw> on 2025-05-01 00:00:00+00:00
[2025-05-26T03:41:04.670+0000] {standard_task_runner.py:57} INFO - Started process 6512 to run task
[2025-05-26T03:41:04.680+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_raw', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpqqsi3adb']
[2025-05-26T03:41:04.686+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask create_table_raw
[2025-05-26T03:41:04.795+0000] {task_command.py:410} INFO - Running <TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [running]> on host 65cea7b09e55
[2025-05-26T03:41:04.942+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-26T03:41:04.969+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-26T03:41:04.995+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_raw, execution_date=20250501T000000, start_date=20250526T034104, end_date=20250526T034104
[2025-05-26T03:41:05.051+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-05-26T03:41:05.118+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-26T03:49:10.386+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:49:10.402+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:49:10.404+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-05-26T03:49:10.434+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): create_table_raw> on 2025-05-01 00:00:00+00:00
[2025-05-26T03:49:10.454+0000] {standard_task_runner.py:57} INFO - Started process 6648 to run task
[2025-05-26T03:49:10.465+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_raw', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpbk5oweui']
[2025-05-26T03:49:10.472+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask create_table_raw
[2025-05-26T03:49:10.567+0000] {task_command.py:410} INFO - Running <TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [running]> on host 65cea7b09e55
[2025-05-26T03:49:10.698+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-26T03:49:10.716+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-26T03:49:10.734+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_raw, execution_date=20250501T000000, start_date=20250526T034910, end_date=20250526T034910
[2025-05-26T03:49:10.795+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-05-26T03:49:10.862+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-26T03:57:30.278+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:57:30.296+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T03:57:30.297+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-05-26T03:57:30.320+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): create_table_raw> on 2025-05-01 00:00:00+00:00
[2025-05-26T03:57:30.336+0000] {standard_task_runner.py:57} INFO - Started process 6809 to run task
[2025-05-26T03:57:30.344+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_raw', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpx7ov1otf']
[2025-05-26T03:57:30.350+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask create_table_raw
[2025-05-26T03:57:30.436+0000] {task_command.py:410} INFO - Running <TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [running]> on host 65cea7b09e55
[2025-05-26T03:57:30.571+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-26T03:57:30.593+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-26T03:57:30.620+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_raw, execution_date=20250501T000000, start_date=20250526T035730, end_date=20250526T035730
[2025-05-26T03:57:30.676+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-05-26T03:57:30.766+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-26T04:05:29.152+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T04:05:29.176+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T04:05:29.177+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-05-26T04:05:29.203+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): create_table_raw> on 2025-05-01 00:00:00+00:00
[2025-05-26T04:05:29.219+0000] {standard_task_runner.py:57} INFO - Started process 89 to run task
[2025-05-26T04:05:29.230+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_raw', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpaz21lfoq']
[2025-05-26T04:05:29.236+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask create_table_raw
[2025-05-26T04:05:29.388+0000] {task_command.py:410} INFO - Running <TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [running]> on host 419e61ae62e7
[2025-05-26T04:05:29.592+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-26T04:05:29.619+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-26T04:05:29.637+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_raw, execution_date=20250501T000000, start_date=20250526T040529, end_date=20250526T040529
[2025-05-26T04:05:29.685+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-05-26T04:05:29.743+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-26T04:17:13.360+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T04:17:13.378+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T04:17:13.378+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-05-26T04:17:13.404+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): create_table_raw> on 2025-05-01 00:00:00+00:00
[2025-05-26T04:17:13.419+0000] {standard_task_runner.py:57} INFO - Started process 293 to run task
[2025-05-26T04:17:13.427+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_raw', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp10ly1bhf']
[2025-05-26T04:17:13.433+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask create_table_raw
[2025-05-26T04:17:13.540+0000] {task_command.py:410} INFO - Running <TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [running]> on host 419e61ae62e7
[2025-05-26T04:17:13.698+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-26T04:17:13.721+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-26T04:17:13.746+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_raw, execution_date=20250501T000000, start_date=20250526T041713, end_date=20250526T041713
[2025-05-26T04:17:13.799+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-05-26T04:17:13.860+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-26T04:41:50.432+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T04:41:50.447+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-26T04:41:50.447+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-05-26T04:41:50.467+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): create_table_raw> on 2025-05-01 00:00:00+00:00
[2025-05-26T04:41:50.488+0000] {standard_task_runner.py:57} INFO - Started process 657 to run task
[2025-05-26T04:41:50.501+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_table_raw', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpxbjz0mj0']
[2025-05-26T04:41:50.506+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask create_table_raw
[2025-05-26T04:41:50.607+0000] {task_command.py:410} INFO - Running <TaskInstance: data_pipeline.create_table_raw scheduled__2025-05-01T00:00:00+00:00 [running]> on host 419e61ae62e7
[2025-05-26T04:41:50.733+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_table_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-26T04:41:50.753+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-26T04:41:50.784+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_table_raw, execution_date=20250501T000000, start_date=20250526T044150, end_date=20250526T044150
[2025-05-26T04:41:50.830+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-05-26T04:41:50.890+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
